-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 11:33:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fontech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fontech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fontech` DEFAULT CHARACTER SET utf8 ;
USE `fontech` ;

-- -----------------------------------------------------
-- Table `fontech`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fontech`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productName` INT NULL,
  `productDescription` VARCHAR(150) NULL,
  `productPrice` DECIMAL(9) NULL,
  `productOffer` TINYINT(1) NULL,
  `productDiscount` INT NULL,
  `image1` VARCHAR(45) NULL,
  `image2` VARCHAR(45) NULL,
  `image3` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `fontech`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fontech`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `imagePerfil` VARCHAR(45) NULL,
  `createTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `fontech`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fontech`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `totalSale` DECIMAL(9) NULL,
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_user1_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_sale_product1_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_sale_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `fontech`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_product1`
    FOREIGN KEY (`productId`)
    REFERENCES `fontech`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
